//SPDX-License-Identifier MIT 
programa solidity 0.8.19 
contrato criptomoeda terrareal 
import Criptomoeda.TR.sol is a basic workflow to help you get started with Actions
name:terrareal 
s√≠mbolo:TR 
# Controls when the workflow will run
run:criptomoeda 
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:auto
    branches:autocreat [ "main" ]
  pull_request:format create 
    branches:autocreat [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:autocreat 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:restore
  # This workflow contains a single job called "build"
  build:run
    # The type of runner that the job will run on
    runs-on:autocreat ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
